### ISSUE TITLE
"An error occured" op vercel

### ISSUE THREAD

**Issue by UnrealThingTriesCode** [HarryDeKat/MagIcal#1]
Om een of andere reden zie ik een error scherm, ik heb het gedeployed met vercel en al mn gegevens ingevoerd
[hier de pagina](https://magicaldev.vercel.app/ical?auth=tochniet=&extrawekenvooruit=1&extrawekenterug=0&InHTMLFormaat=false&ReadalbeCal=false&ShowToetsen=true&ShowEvents=true&ShowHuiswerk=true&ShowAfgerond=true&ShowOpdrachten=true&ShowAbsenties=true&SkipEmpty=true&ShowUitval=false&ShowPersonalChanges=false&ShowUitvalMetcancelled=false&Toetsvooruitblik=false&Herinneringen=MzA=&summaryname=sussyamong==) de auth heb ik uit de link gehaald

**Comment by HarryDeKat** [comment]
Ik had dit waarschijnlijk iets beter moeten aangeven, maar je hebt de verkeerde public en waarschijnlijk private key gebruikt. [Zo](https://magister-naar-icalendar.vercel.app/publickey.js) hoort hij eruit te zien, maar bij jou ziet hij er [zo](https://magicaldev.vercel.app/publickey.js) uit. In de ReadMe staat hoe je de keys had moeten genereren, maar ik geef inderdaad toe dat het niet helemaal duidelijk is. Sorry hiervoor.

**Comment by HarryDeKat** [comment]
Mocht je het nog oplossen mag je de issue sluiten. En als er nog verdere vragen zijn mag je die uiteraard ook stellen.

**Comment by UnrealThingTriesCode** [comment]
aha, duidelijk! thanks
