### ISSUE TITLE
Microsoft account: "Vercel: An error occurred"

### ISSUE THREAD

**Issue by HexaNLD** [HarryDeKat/MagIcal#3]
**Controle**
- [x] Ik kon in de readme geen oplossing voor mijn fout vinden.
- [x] Ik heb de private- en publickey correct gegenereerd.

**Op het moment gebruikt instellingen (plakken van link is genoeg)**
```
https://magister-naar-icalendar-ochre.vercel.app/ical?auth=&extrawekenvooruit=1&extrawekenterug=0&InHTMLFormaat=false&ReadalbeCal=false&ShowToetsen=true&ShowEvents=true&ShowHuiswerk=true&ShowAfgerond=true&ShowOpdrachten=true&ShowAbsenties=true&SkipEmpty=true&ShowUitval=false&ShowPersonalChanges=false&ShowUitvalMetcancelled=false&Toetsvooruitblik=false&Herinneringen=MzA=&summaryname=JHtWYWtuYWFtfQ==
```

**Beschijf de fout**
Ik heb het correct gedeployed met behulp van Vercel, maar krijg de hele tijd dit scherm als ik een link probeer te genereren. Ik vermoed dat het misschien te maken zou kunnen hebben met het feit dat mijn Magister gebruik maakt van inloggen via een Microsoft-account.

<img width="1286" alt="Scherm­afbeelding 2024-08-17 om 13 42 02" src="https://github.com/user-attachments/assets/6cd6f8a6-3911-4050-83b4-36431296591d">

**Comment by HarryDeKat** [comment]
Hey HexaNLD, dat kan kloppen inderdaad. Toen ik dit had geschreven een aantal jaar terug heb ik geen rekening gehouden met andere login methodes, waardoor het alleen werkt als je een gebruikersnaam en wachtwoord van Magister hebt. Is een beetje zuur, dat weet ik, maar ik kan er helaas niet veel meer aan doen. De manier waarop het geschreven is betekent dat het niet mogelijk is om met tokens, een manier waardoor je met alles kan inloggen, te werken, wat zou betekenen dat ik alles moet herschrijven. Ik heb volgens mij bij issue #2 een iets betere beschrijving gegeven over waarom het niet werkt op het moment, dus wellicht kun je daar nog even naar kijken. Ik kan het op zich wel herschrijven en ik ben er ook al een keer aan begonnen, maar omdat ik het zelf niet nodig heb is er niet bijzonder veel motivatie. Wellicht dat ik dit jaar er nog een keer naar kijk, maar dat kan ik niet met zekerheid zeggen.
